name: daily_fitness
description: Daily Fitness cross-platform e-commerce app using Flutter and Firebase.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  firebase_storage: ^13.4.1
  firebase_messaging: ^16.2.2
  google_sign_in: ^6.1.0
  intl: ^0.18.0
  flutter_svg: ^2.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
